"""empty message

Revision ID: a32ba9f82bdd
Revises: 2914cfb69c8f
Create Date: 2020-09-09 04:48:59.628322

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a32ba9f82bdd'
down_revision = '2914cfb69c8f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('playlistsongs_track_key', 'playlistsongs', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('playlistsongs_track_key', 'playlistsongs', ['track'])
    # ### end Alembic commands ###
